kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-pd-csi-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: gcp-pd-csi-driver-controller-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: gcp-pd-external-provisioner-role
  apiGroup: rbac.authorization.k8s.io
